# Настройки SleepSkip
settings:
  required-type: "percent"  # "fixed" или "percent"
  required-value: 50        # Значение порога (число или процент)

  ignore-afk: true         # Исключать ли AFK-игроков (CMI/EssentialsX)
  skip-rain: true          # Пропускать ли дождь при пропуске ночи
  per-world: false         # Использовать разные настройки для миров
  use-actionbar: true      # Использовать экшен-бар для уведомлений

messages:
  nightSkipped: "<#F6AD72>Ночь пропущена! Доброе утро!"
  sleepingStatus: "<#EC9793>{sleeping}/{needed} &fигроков спит. Нужно <#EC9793>{needed} &fдля пропуска ночи!"
  not-enough: "&cНедостаточно игроков спит!"